---
- name: Hello World!
  hosts: all
 
  tasks:
 
  - name: Download machine agent
    unarchive:
      src: https://s3.amazonaws.com/hertertcdn/agents/machineagent-bundle-64bit-linux-4.4.3.1214.zip
      dest: /opt/appdynamics/machineagent
      remote_src: yes
